version: '3.8'

services:
  portfolio-prod:
    image: nginx:alpine
    container_name: portfolio-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../portfolio-prod/web-resume:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    restart: unless-stopped
    networks:
      - portfolio

networks:
  portfolio:
    driver: bridge
